version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: zope-interface
    versions:
    - 5.3.0
